<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Claim {{ $claim->claim_number }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #1f2937;
            margin: 24px;
        }
        h1 {
            font-size: 18px;
            margin: 0 0 4px 0;
            color: #0b4f6c;
        }
        .subtitle {
            margin-bottom: 16px;
            color: #4b5563;
        }
        .section {
            border: 1px solid #d1d5db;
            border-radius: 6px;
            margin-bottom: 12px;
            padding: 10px;
        }
        .section-title {
            font-weight: bold;
            font-size: 13px;
            margin-bottom: 8px;
            color: #0b4f6c;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        td {
            padding: 4px 0;
            vertical-align: top;
        }
        td.label {
            width: 38%;
            font-weight: bold;
            color: #4b5563;
        }
        .footer {
            margin-top: 18px;
            font-size: 10px;
            color: #6b7280;
            text-align: right;
        }
    </style>
</head>
<body>
    <h1>NATIONAL MEDICAL AID CLAIM FORM</h1>
    <div class="subtitle">Claim #: {{ $claim->claim_number }}</div>

    <div class="section">
        <div class="section-title">Patient Information</div>
        <table>
            <tr>
                <td class="label">Name</td>
                <td>{{ $claim->patient->full_name ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td class="label">Medical Aid Provider</td>
                <td>{{ $claim->medical_aid_provider ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td class="label">Medical Aid Number</td>
                <td>{{ $claim->medical_aid_number ?? 'N/A' }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Claim Details</div>
        <table>
            <tr>
                <td class="label">Date of Service</td>
                <td>{{ $claim->date_of_service ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td class="label">Amount Claimed</td>
                <td>${{ number_format((float) ($claim->amount_claimed ?? 0), 2) }}</td>
            </tr>
            <tr>
                <td class="label">Status</td>
                <td>{{ $claim->status ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td class="label">Diagnosis</td>
                <td>{{ $claim->consultation->diagnosis ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td class="label">Treatment</td>
                <td>{{ $claim->consultation->prescribed_treatment ?? 'N/A' }}</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        Generated by CareClinic on {{ now()->format('Y-m-d H:i') }}
    </div>
</body>
</html>
